// Languages
const LANGUAGES = {
    en: { name: 'English', flag: '🇬🇧' }, fr: { name: 'Français', flag: '🇫🇷' }, es: { name: 'Español', flag: '🇪🇸' }, de: { name: 'Deutsch', flag: '🇩🇪' }, ru: { name: 'Русский', flag: '🇷🇺' }, ja: { name: '日本語', flag: '🇯🇵' }, zh: { name: '中文', flag: '🇨🇳' },
};

// Translations Placeholder
const TRANSLATIONS = {
    en: {
        gifModal: {
            title: "📹 High Quality GIF Capture",
            body: "To get a perfect result, we need to capture the screen:",
            step1: "Select the <strong>\"Tab\"</strong> option.",
            step2: "Choose <strong>this page</strong> from the list.",
            step3: "Click <strong>\"Share\"</strong>.",
            note: "The mouse will be automatically hidden and the card cropped.",
            warning: "Using maximum settings (60 FPS / 4K) may take longer and use high CPU.",
            fpsLabel: "FPS",
            qualityLabel: "Quality (Height)",
            fpsNormal: "15 FPS (Normal)",
            fpsCinema: "24 FPS (Cinema)",
            fpsSmooth: "30 FPS (Smooth)",
            fpsUltra: "60 FPS (Ultra)",
            qualitySD: "480p (SD)",
            qualityNormal: "720p (HD)",
            qualityHigh: "1080p (Full HD)",
            qualityQHD: "1440p (QHD)",
            qualityUltra: "4K (UHD)",
            cancel: "Cancel",
            start: "Start Capture", loadingLibs: "⏳ Loading libs...", capturing: "📸 Capturing...", encoding: "⚙️ Encoding..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'Create your own personalized collectible cards',
        hoverHint: '✨ Hover over the card to intensify the effect ✨',
        elements: { Fire: 'Fire', Water: 'Water', Nature: 'Nature', Electric: 'Electric', Mystic: 'Mystic', Fighting: 'Fighting', Shadow: 'Shadow', Metal: 'Metal', Light: 'Light', Dragon: 'Dragon', Ice: 'Ice', Neutral: 'Neutral' },
        effects: { none: { name: 'None', description: 'No effect' }, holographic: { name: 'Holographic', description: 'Classic rainbow effect' }, rainbow: { name: 'Rainbow', description: 'Animated multicolor gradient' }, gold: { name: 'Gold', description: 'Luxurious golden reflections' }, silver: { name: 'Silver', description: 'Metallic silver reflections' }, prismatic: { name: 'Prismatic', description: 'Refracting crystal effect' }, neon: { name: 'Neon', description: 'Vibrant neon glow' }, galaxy: { name: 'Galaxy', description: 'Starry cosmic effect' }, fire: { name: 'Flames', description: 'Animated flame effect' }, ice: { name: 'Frost', description: 'Sparkling ice effect' } },
        stages: ['Base', 'Stage 1', 'Stage 2', 'Special', 'Legendary', 'Mythic', 'Ultra'],
        rarities: { common: 'Common', uncommon: 'Uncommon', rare: 'Rare', epic: 'Epic', legendary: 'Legendary', mythic: 'Mythic' },
        sections: { image: 'Image', basicInfo: 'Basic Information', rarityEffects: 'Effects', abilities: 'Abilities', stats: 'Statistics', appearance: 'Appearance', cardStyle: 'Card Style', textStyle: 'Text Style', particles: 'Particles', abilityStyle: 'Ability Style', reset: 'Reset', cardBack: 'Card Back' },
        labels: { name: 'Name', hp: 'Hit Points', element: 'Element', stage: 'Stage', description: 'Description', author: 'Author', rarity: 'Rarity', effect: 'Effect', weakness: 'Weakness', resistance: 'Resistance', retreatCost: 'Retreat Cost', abilityName: 'Ability Name', damage: 'Damage', energyCost: 'Energy Cost', abilityDesc: 'Abilities Description', borderColor: 'Border Color', backgroundColor: 'Card Background', abilityBackground: 'Ability Background', textColor: 'Text Color', font: 'Font', size: 'Size', weight: 'Weight', zoom: 'Zoom', presets: 'Presets', backgroundStyle: 'Background Style', solid: 'Solid', gradient: 'Gradient', cardInner: 'Card Inner', primaryColor: 'Primary Color', secondaryColor: 'Secondary Color', nameColor: 'Name Color', hpColor: 'HP Color', typeColor: 'Type Color', descColor: 'Description Color', statsColor: 'Stats Color', authorColor: 'Author Color', particleEmoji: 'Particle Emoji', animation: 'Animation', color: 'Color', stats: 'Stats', texture: 'Texture' },
        buttons: { addAbility: '+ Add Ability', remove: 'Remove', change: 'Change', recenter: 'Recenter', download: 'Download', autoRotate: '3D View', resetCard: '🔄 Reset Card', save: 'Save', load: 'Load', deleteAll: 'Delete All', import: 'Import JSON', storage: 'Local Storage 💾', json: 'JSON', showFront: 'Show Front', flipCard: 'Flip Card' },
        deckBuilder: { title: 'Deck Builder', subtitle: 'A4 Print Sheet (9 cards)', clear: 'Clear', export: 'Download Sheet', library: 'Library', full: 'Grid is full!', exporting: 'Preparing sheet...', success: 'Sheet downloaded!', successPdf: 'PDF downloaded!', error: 'Export failed', errorLoad: 'Could not load library', clickToRemove: 'Click to remove', settings: 'Settings', paperFormat: 'Paper', cardCount: 'Cards', cardSize: 'Card Size', presets: 'Quick Presets', presetStandard: 'Standard', presetCompact: 'Compact', presetMini: 'Mini', presetMax: 'Max', cards: 'cards', card: 'card', currentLayout: 'Layout', customize: 'Customize' },
        checkboxes: { showHP: 'Show hit points', showWeakRes: 'Show weakness/resistance', showRetreat: 'Show retreat cost', showDescription: 'Show description', showTexture: 'Show texture pattern', showParticles: 'Show particles', showDamage: 'Show damage' },
        imageEditor: { dropHint: 'Drag & drop an image here', orClick: 'or click to select', formats: 'PNG,JPG,GIF,WEBP (max 15MB)', loading: 'Loading...', unsupportedFormat: 'Unsupported format. Use PNG,JPG,GIF or WEBP.', fileTooLarge: 'File too large. Maximum 15MB.', searchPlaceholder: 'Type...' },
        download: { title: '📥 Download', pngTitle: 'Transparent PNG image', jpgTitle: 'JPG image with background', gifTitle: 'Animated GIF (3 seconds)', webpTitle: 'WebP Image', htmlTitle: 'Interactive HTML file', capturing: '⏳ Capturing...', encoding: '⚙️ Encoding...', pngDesc: 'High quality, transparent', jpgDesc: 'Small size, white background', webpDesc: 'Optimized for web', gifDesc: 'Animated capture (3s)', frontSide: 'Front Side', backSide: 'Back Side', frontHint: 'Flip the card to download the back', backHint: 'Flip the card to download the front', gifBackDisabled: 'GIF is only available for the front side' },
        card: { hp: 'HP', weakness: 'Weakness', resistance: 'Resistance', cost: 'Cost', illus: 'Illus.' },
        storage: { tabSave: 'Save Card', tabLoad: 'Load Card' },
        json: { modalTitle: 'Import / Export JSON', importTitle: 'Import Card', exportTitle: 'Export Card', importBtn: 'Import JSON File', exportBtn: 'Export JSON File', help: 'Save your card as a .json file to back it up or share it. You can import it back later to edit it again.', successImport: 'Card imported successfully!', errorImport: 'Invalid JSON file.' },
        defaults: { newAbility: 'New Ability', cardName: 'My Creature', description: 'A mysterious creature with incredible powers.', author: 'Creator', attackName1: 'Fireball', attackDesc1: 'Flip a coin. If heads, the Defending Pokémon is now Burned.', attackName2: 'Flamethrower', attackDesc2: 'Discard an Energy attached to this Pokémon.' }, notifications: { success: 'Success', error: 'Error', info: 'Information', warning: 'Warning' },
        display: { title: 'Display Options' },
        tabs: { info: 'Info', content: 'Content', visual: 'Visual', style: 'Style', colors: 'Colors' },
        common: { cancel: 'Cancel', close: 'Close', legalNotice: 'Legal Notice' },
        prompts: { resetConfirm: 'Reset all card data?', saveHint: 'Your card (text + image) will be saved locally.', saveSuccess: 'Card saved successfully!', loadConfirm: 'Load this card? Unsaved changes will be lost.', deleteConfirm: 'Delete this saved card?', deleteAllConfirm: 'Delete all saved cards? This cannot be undone.', allDeleted: 'All cards deleted', noSaves: 'No saved cards found.', quotaError: 'Storage full! Try deleting old cards.', saveError: 'Error saving card.', autoDeleteInfo: 'Saved cards are automatically deleted after 30 days.' },
        textures: { none: 'None', grid: 'Grid', scales: 'Scales', cross: 'Cross', stars: 'Stars', hexagons: 'Hexagons', lines: 'Lines', dots: 'Dots', waves: 'Waves', circuit: 'Circuit' },
        animations: { fire: 'Rising', water: 'Bubbles', nature: 'Floating', electric: 'Sparks', mystic: 'Magic', fighting: 'Impact', shadow: 'Fade', metal: 'Gears', light: 'Radiate', dragon: 'Majestic', ice: 'Snow', neutral: 'Subtle' },
        fontWeights: { normal: 'Normal', bold: 'Bold', black: 'Black' },
        cardBackText: 'CARD BACK',
        cardBackOptions: { title: 'Default Back Style', primaryColor: 'Primary Color', secondaryColor: 'Secondary Color', gradientType: 'Gradient Type', radial: 'Radial', linear: 'Linear', angle: 'Angle', elements: 'Decorative Elements', centerIcon: 'Center Icon', cornerIcons: 'Corner Icons', frame: 'Frame', texture: 'Texture', border: 'Border' }
    },
    fr: {
        gifModal: {
            title: "📹 Capture GIF Haute Qualité",
            body: "Pour obtenir un résultat parfait, nous devons capturer l'écran :",
            step1: "Sélectionnez l'option <strong>\"Onglet\"</strong>.",
            step2: "Choisissez <strong>cette page</strong> dans la liste.",
            step3: "Cliquez sur <strong>\"Partager\"</strong>.",
            note: "La souris sera automatiquement masquée et la carte recadrée.",
            warning: "L'utilisation des paramètres maximum (60 IPS / 4K) peut prendre plus de temps et utiliser beaucoup de CPU.",
            fpsLabel: "IPS",
            qualityLabel: "Qualité (Hauteur)",
            fpsNormal: "15 IPS (Normal)",
            fpsCinema: "24 IPS (Cinéma)",
            fpsSmooth: "30 IPS (Fluide)",
            fpsUltra: "60 IPS (Ultra)",
            qualitySD: "480p (SD)",
            qualityNormal: "720p (HD)",
            qualityHigh: "1080p (Full HD)",
            qualityQHD: "1440p (QHD)",
            qualityUltra: "4K (UHD)",
            cancel: "Annuler",
            start: "Lancer la capture", loadingLibs: "⏳ Chargement...", capturing: "📸 Capture...", encoding: "⚙️ Encodage..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'Créez vos propres cartes à collectionner personnalisées',
        hoverHint: '✨ Survolez la carte pour intensifier l\'effet ✨',
        elements: { Fire: 'Feu', Water: 'Eau', Nature: 'Nature', Electric: 'Électrique', Mystic: 'Mystique', Fighting: 'Combat', Shadow: 'Ombre', Metal: 'Métal', Light: 'Lumière', Dragon: 'Dragon', Ice: 'Glace', Neutral: 'Neutre' },
        effects: { none: { name: 'Aucun', description: 'Pas d\'effet' }, holographic: { name: 'Holographique', description: 'Effet arc-en-ciel classique' }, rainbow: { name: 'Arc-en-ciel', description: 'Dégradé multicolore animé' }, gold: { name: 'Doré', description: 'Reflets dorés luxueux' }, silver: { name: 'Argenté', description: 'Reflets argentés métalliques' }, prismatic: { name: 'Prismatique', description: 'Effet cristal réfractant' }, neon: { name: 'Néon', description: 'Lueur néon vibrante' }, galaxy: { name: 'Galaxie', description: 'Effet cosmique étoilé' }, fire: { name: 'Flammes', description: 'Effet de flammes animées' }, ice: { name: 'Givré', description: 'Effet de glace scintillante' } },
        stages: ['Base', 'Évolution 1', 'Évolution 2', 'Spécial', 'Légendaire', 'Mythique', 'Ultra'],
        rarities: { common: 'Commune', uncommon: 'Peu commune', rare: 'Rare', epic: 'Épique', legendary: 'Légendaire', mythic: 'Mythique' },
        sections: { image: 'Image', basicInfo: 'Informations de base', rarityEffects: 'Effets', abilities: 'Capacités', stats: 'Statistiques', appearance: 'Apparence', cardStyle: 'Style de carte', textStyle: 'Style du texte', particles: 'Particules', abilityStyle: 'Style des capacités', reset: 'Réinitialiser', cardBack: 'Dos de carte' },
        labels: { name: 'Nom', hp: 'Points de vie', element: 'Élément', stage: 'Stade', description: 'Description', author: 'Auteur', rarity: 'Rareté', effect: 'Effet', weakness: 'Faiblesse', resistance: 'Résistance', retreatCost: 'Coût de retraite', abilityName: 'Nom de la capacité', damage: 'Dégâts', energyCost: 'Coût en énergie', abilityDesc: 'Description des capacités', borderColor: 'Couleur de bordure', backgroundColor: 'Fond de carte', abilityBackground: 'Fond des capacités', textColor: 'Couleur du texte', font: 'Police', size: 'Taille', weight: 'Graisse', zoom: 'Zoom', presets: 'Préréglages', backgroundStyle: 'Style de fond', solid: 'Uni', gradient: 'Dégradé', cardInner: 'Intérieur de la carte', primaryColor: 'Couleur principale', secondaryColor: 'Couleur secondaire', nameColor: 'Couleur du nom', hpColor: 'Couleur des PV', typeColor: 'Couleur du type', descColor: 'Couleur de description', statsColor: 'Couleur des stats', authorColor: 'Couleur de l\'auteur', particleEmoji: 'Emoji de particule', animation: 'Animation', color: 'Couleur', stats: 'Stats', texture: 'Texture' },
        buttons: { addAbility: '+ Ajouter', remove: 'Supprimer', change: 'Changer', recenter: 'Recentrer', download: 'Télécharger', autoRotate: 'Aperçu 3D', resetCard: '🔄 Réinitialiser', save: 'Sauvegarder', load: 'Charger', deleteAll: 'Tout supprimer', import: 'Importer JSON', storage: 'Sauvegardes 💾', json: 'JSON', showFront: 'Voir Recto', flipCard: 'Retourner' },
        deckBuilder: { title: 'Constructeur de Deck', subtitle: 'Feuille A4 (9 cartes)', clear: 'Effacer', export: 'Télécharger la feuille', library: 'Bibliothèque', full: 'La grille est pleine !', exporting: 'Préparation...', success: 'Feuille téléchargée !', successPdf: 'PDF téléchargé !', error: 'Échec de l\'export', errorLoad: 'Impossible de charger la bibliothèque', clickToRemove: 'Cliquer pour retirer', settings: 'Paramètres', paperFormat: 'Format', cardCount: 'Cartes', cardSize: 'Taille', presets: 'Préréglages rapides', presetStandard: 'Standard', presetCompact: 'Compact', presetMini: 'Mini', presetMax: 'Max', cards: 'cartes', card: 'carte', currentLayout: 'Disposition', customize: 'Personnaliser' },
        checkboxes: { showHP: 'Afficher les points de vie', showWeakRes: 'Afficher faiblesse/résistance', showRetreat: 'Afficher le coût de retraite', showDescription: 'Afficher la description', showTexture: 'Afficher le motif', showParticles: 'Afficher les particules', showDamage: 'Afficher les dégâts' },
        imageEditor: { dropHint: 'Glissez-déposez une image ici', orClick: 'ou cliquez pour sélectionner', formats: 'PNG,JPG,GIF,WEBP (max 15Mo)', loading: 'Chargement...', unsupportedFormat: 'Format non supporté. Utilisez PNG,JPG,GIF ou WEBP.', fileTooLarge: 'Fichier trop volumineux. Maximum 15Mo.', searchPlaceholder: 'Tapez...' },
        download: { title: '📥 Télécharger', pngTitle: 'Image PNG transparente', jpgTitle: 'Image JPG avec fond', gifTitle: 'GIF animé (3 secondes)', webpTitle: 'Image WebP', htmlTitle: 'Fichier HTML interactif', capturing: '⏳ Capture...', encoding: '⚙️ Encodage...', pngDesc: 'Haute qualité, transparent', jpgDesc: 'Fichier léger, fond blanc', webpDesc: 'Optimisé pour le web', gifDesc: 'Capture animée (3s)', frontSide: 'Face Avant', backSide: 'Face Arrière', frontHint: 'Retournez la carte pour télécharger le dos', backHint: 'Retournez la carte pour télécharger la face', gifBackDisabled: 'Le GIF n\'est disponible que pour la face avant' },
        card: { hp: 'PV', weakness: 'Faiblesse', resistance: 'Résistance', cost: 'Coût', illus: 'Illus.' },
        storage: { tabSave: 'Sauvegarder', tabLoad: 'Charger' },
        json: { modalTitle: 'Import / Export JSON', importTitle: 'Importer une carte', exportTitle: 'Exporter la carte', importBtn: 'Importer le fichier JSON', exportBtn: 'Exporter le fichier JSON', help: 'Sauvegardez votre carte en tant que fichier .json pour la conserver ou la partager. Vous pourrez la réimporter plus tard.', successImport: 'Carte importée avec succès !', errorImport: 'Fichier JSON invalide.' },
        defaults: { newAbility: 'Nouvelle Capacité', cardName: 'Ma Créature', description: 'Une créature mystérieuse aux pouvoirs incroyables.', author: 'Créateur', attackName1: 'Boule de Feu', attackDesc1: 'Lancez une pièce. Si c\'est face, le Pokémon Défenseur est maintenant Brûlé.', attackName2: 'Lance-Flammes', attackDesc2: 'Défaussez une Énergie attachée à ce Pokémon.' }, notifications: { success: 'Succès', error: 'Erreur', info: 'Information', warning: 'Attention' },
        display: { title: 'Options d\'affichage' },
        tabs: { info: 'Infos', content: 'Contenu', visual: 'Visuel', style: 'Style', colors: 'Couleurs' },
        common: { cancel: 'Annuler', close: 'Fermer', legalNotice: 'Mentions légales' },
        prompts: { resetConfirm: 'Réinitialiser toutes les données de la carte ?', saveHint: 'Votre carte (texte + image) sera sauvegardée localement.', saveSuccess: 'Carte sauvegardée avec succès !', loadConfirm: 'Charger cette carte ? Les modifications non sauvegardées seront perdues.', deleteConfirm: 'Supprimer cette carte ?', deleteAllConfirm: 'Supprimer toutes les cartes ? Cette action est irréversible.', allDeleted: 'Toutes les cartes supprimées', noSaves: 'Aucune carte sauvegardée.', quotaError: 'Espace insuffisant ! Supprimez des anciennes cartes.', saveError: 'Erreur lors de la sauvegarde.', autoDeleteInfo: 'Les cartes sont supprimées après 30 jours.' },
        textures: { none: 'Aucun', grid: 'Grille', scales: 'Écailles', cross: 'Croix', stars: 'Étoiles', hexagons: 'Hexagones', lines: 'Lignes', dots: 'Points', waves: 'Vagues', circuit: 'Circuit' },
        animations: { fire: 'Montant', water: 'Bulles', nature: 'Flottant', electric: 'Étincelles', mystic: 'Magie', fighting: 'Impact', shadow: 'Fondu', metal: 'Engrenages', light: 'Rayonnement', dragon: 'Majestueux', ice: 'Neige', neutral: 'Subtil' },
        fontWeights: { normal: 'Normal', bold: 'Gras', black: 'Noir' },
        cardBackText: 'DOS DE CARTE',
        cardBackOptions: { title: 'Style par défaut', primaryColor: 'Couleur principale', secondaryColor: 'Couleur secondaire', gradientType: 'Type de dégradé', radial: 'Radial', linear: 'Linéaire', angle: 'Angle', elements: 'Éléments décoratifs', centerIcon: 'Icône centrale', cornerIcons: 'Icônes de coins', frame: 'Cadre', texture: 'Texture', border: 'Contour' }
    },

    es: {
        gifModal: {
            title: "📹 Captura GIF de Alta Calidad",
            body: "Para obtener un resultado perfecto, necesitamos capturar la pantalla:",
            step1: "Selecciona la opción <strong>\"Pestaña\"</strong>.",
            step2: "Elige <strong>esta página</strong> de la lista.",
            step3: "Haz clic en <strong>\"Compartir\"</strong>.",
            note: "El ratón se ocultará automáticamente y la carta se recortará.",
            warning: "El uso de la configuración máxima (60 FPS / 4K) puede tardar más y consumir mucha CPU.",
            fpsLabel: "FPS",
            qualityLabel: "Calidad (Altura)",
            fpsNormal: "15 FPS (Normal)",
            fpsCinema: "24 FPS (Cine)",
            fpsSmooth: "30 FPS (Fluido)",
            fpsUltra: "60 FPS (Ultra)",
            qualitySD: "480p (SD)",
            qualityNormal: "720p (HD)",
            qualityHigh: "1080p (Full HD)",
            qualityQHD: "1440p (QHD)",
            qualityUltra: "4K (UHD)",
            cancel: "Cancelar",
            start: "Iniciar Captura", loadingLibs: "⏳ Cargando...", capturing: "📸 Capturando...", encoding: "⚙️ Codificando..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'Crea tus propias cartas coleccionables personalizadas',
        hoverHint: '✨ Pasa el cursor sobre la carta para intensificar el efecto ✨',
        elements: { Fire: 'Fuego', Water: 'Agua', Nature: 'Naturaleza', Electric: 'Eléctrico', Mystic: 'Místico', Fighting: 'Lucha', Shadow: 'Sombra', Metal: 'Metal', Light: 'Luz', Dragon: 'Dragón', Ice: 'Hielo', Neutral: 'Neutral' },
        effects: { none: { name: 'Ninguno', description: 'Sin efecto' }, holographic: { name: 'Holográfico', description: 'Efecto arcoíris clásico' }, rainbow: { name: 'Arcoíris', description: 'Degradado multicolor animado' }, gold: { name: 'Dorado', description: 'Reflejos dorados lujosos' }, silver: { name: 'Plateado', description: 'Reflejos metálicos plateados' }, prismatic: { name: 'Prismático', description: 'Efecto cristal refractante' }, neon: { name: 'Neón', description: 'Brillo neón vibrante' }, galaxy: { name: 'Galaxia', description: 'Efecto cósmico estrellado' }, fire: { name: 'Llamas', description: 'Efecto de llamas animadas' }, ice: { name: 'Escarcha', description: 'Efecto de hielo brillante' } },
        stages: ['Base', 'Fase 1', 'Fase 2', 'Especial', 'Legendario', 'Mítico', 'Ultra'],
        rarities: { common: 'Común', uncommon: 'Poco común', rare: 'Rara', epic: 'Épica', legendary: 'Legendaria', mythic: 'Mítica' },
        sections: { image: 'Imagen', basicInfo: 'Información básica', rarityEffects: 'Efectos', abilities: 'Habilidades', stats: 'Estadísticas', appearance: 'Apariencia', cardStyle: 'Estilo de carta', textStyle: 'Estilo de texto', particles: 'Partículas', abilityStyle: 'Estilo de habilidad', reset: 'Reiniciar', cardBack: 'Reverso de carta' },
        labels: { name: 'Nombre', hp: 'Puntos de vida', element: 'Elemento', stage: 'Fase', description: 'Descripción', author: 'Autor', rarity: 'Rareza', effect: 'Efecto', weakness: 'Debilidad', resistance: 'Resistencia', retreatCost: 'Coste de retirada', abilityName: 'Nombre de habilidad', damage: 'Daño', energyCost: 'Coste de energía', abilityDesc: 'Descripción de habilidades', borderColor: 'Color del borde', backgroundColor: 'Fondo de carta', abilityBackground: 'Fondo de habilidad', textColor: 'Color del texto', font: 'Fuente', size: 'Tamaño', weight: 'Peso', zoom: 'Zoom', presets: 'Preajustes', backgroundStyle: 'Estilo de fondo', solid: 'Sólido', gradient: 'Degradado', cardInner: 'Interior de la carta', primaryColor: 'Color primario', secondaryColor: 'Color secundario', nameColor: 'Color del nombre', hpColor: 'Color de PV', typeColor: 'Color del tipo', descColor: 'Color de descripción', statsColor: 'Color de estadísticas', authorColor: 'Color del autor', particleEmoji: 'Emoji de partícula', animation: 'Animación', color: 'Color', stats: 'Estad.', texture: 'Textura' },
        buttons: { addAbility: '+ Añadir', remove: 'Eliminar', change: 'Cambiar', recenter: 'Recentrar', download: 'Descargar', autoRotate: 'Vista 3D', resetCard: '🔄 Reiniciar', save: 'Guardar', load: 'Cargar', deleteAll: 'Borrar todo', import: 'Importar JSON', storage: 'Guardados 💾', json: 'JSON', showFront: 'Ver Frente', flipCard: 'Voltear' },
        deckBuilder: { title: 'Constructor de Mazo', subtitle: 'Hoja A4 (9 cartas)', clear: 'Limpiar', export: 'Descargar Hoja', library: 'Biblioteca', full: '¡La cuadrícula está llena!', exporting: 'Preparando...', success: '¡Hoja descargada!', successPdf: '¡PDF descargado!', error: 'Fallo de exportación', errorLoad: 'No se pudo cargar la biblioteca', clickToRemove: 'Clic para quitar', settings: 'Ajustes', paperFormat: 'Formato', cardCount: 'Cartas', cardSize: 'Tamaño', presets: 'Preajustes rápidos', presetStandard: 'Estándar', presetCompact: 'Compacto', presetMini: 'Mini', presetMax: 'Max', cards: 'cartas', card: 'carta', currentLayout: 'Diseño', customize: 'Personalizar' },
        checkboxes: { showHP: 'Mostrar puntos de vida', showWeakRes: 'Mostrar debilidad/resistencia', showRetreat: 'Mostrar coste de retirada', showDescription: 'Mostrar descripción', showTexture: 'Mostrar patrón', showParticles: 'Mostrar partículas', showDamage: 'Mostrar daño' },
        imageEditor: { dropHint: 'Arrastra y suelta una imagen aquí', orClick: 'o haz clic para seleccionar', formats: 'PNG,JPG,GIF,WEBP (máx 15MB)', loading: 'Cargando...', unsupportedFormat: 'Formato no soportado. Use PNG,JPG,GIF o WEBP.', fileTooLarge: 'Archivo demasiado grande. Máximo 15MB.', searchPlaceholder: 'Escriba...' },
        download: { title: '📥 Descargar', pngTitle: 'Imagen PNG transparente', jpgTitle: 'Imagen JPG con fondo', gifTitle: 'GIF animado (3 segundos)', webpTitle: 'Imagen WebP', htmlTitle: 'Archivo HTML interactivo', capturing: '⏳ Capturando...', encoding: '⚙️ Codificando...', pngDesc: 'Alta calidad, transparente', jpgDesc: 'Tamaño reducido, fondo blanco', webpDesc: 'Optimizado para web', gifDesc: 'Captura animada (3s)', frontSide: 'Cara Frontal', backSide: 'Cara Trasera', frontHint: 'Voltea la carta para descargar el reverso', backHint: 'Voltea la carta para descargar el frente', gifBackDisabled: 'GIF solo disponible para la cara frontal' },
        card: { hp: 'PS', weakness: 'Debilidad', resistance: 'Resistencia', cost: 'Coste', illus: 'Illus.' },
        storage: { tabSave: 'Guardar', tabLoad: 'Cargar' },
        json: { modalTitle: 'Importar / Exportar JSON', importTitle: 'Importar carta', exportTitle: 'Exportar carta', importBtn: 'Importar archivo JSON', exportBtn: 'Exportar archivo JSON', help: 'Guarda tu carta como archivo .json para conservarla o compartirla.', successImport: '¡Carta importada con éxito!', errorImport: 'Archivo JSON inválido.' },
        defaults: { newAbility: 'Nueva Habilidad', cardName: 'Mi Criatura', description: 'Una criatura misteriosa con poderes increíbles.', author: 'Creador', attackName1: 'Bola de Fuego', attackDesc1: 'Lanza una moneda. Si sale cara, el Pokémon Defensor pasa a estar Quemado.', attackName2: 'Lanzallamas', attackDesc2: 'Descarta una Energía unida a este Pokémon.' }, notifications: { success: 'Éxito', error: 'Error', info: 'Información', warning: 'Advertencia' },
        display: { title: 'Opciones de visualización' },
        tabs: { info: 'Info', content: 'Contenido', visual: 'Visual', style: 'Estilo', colors: 'Colores' },
        common: { cancel: 'Cancelar', close: 'Cerrar', legalNotice: 'Aviso legal' },
        prompts: { resetConfirm: '¿Restablecer todos los datos de la carta?', saveHint: 'Tu carta (texto + imagen) se guardará localmente.', saveSuccess: '¡Carta guardada con éxito!', loadConfirm: '¿Cargar esta carta? Se perderán los cambios no guardados.', deleteConfirm: '¿Eliminar esta carta guardada?', deleteAllConfirm: '¿Eliminar todas las cartas? Esta acción no se puede deshacer.', allDeleted: 'Todas las cartas eliminadas', noSaves: 'No se encontraron cartas guardadas.', quotaError: '¡Almacenamiento lleno! Elimina cartas antiguas.', saveError: 'Error al guardar la carta.', autoDeleteInfo: 'Las cartas se borran tras 30 días.' },
        textures: { none: 'Ninguno', grid: 'Cuadrícula', scales: 'Escamas', cross: 'Cruz', stars: 'Estrellas', hexagons: 'Hexágonos', lines: 'Líneas', dots: 'Puntos', waves: 'Olas', circuit: 'Circuito' },
        animations: { fire: 'Ascendente', water: 'Burbujas', nature: 'Flotante', electric: 'Chispas', mystic: 'Magia', fighting: 'Impacto', shadow: 'Desvanecer', metal: 'Engranajes', light: 'Resplandor', dragon: 'Majestuoso', ice: 'Nieve', neutral: 'Sutil' },
        fontWeights: { normal: 'Normal', bold: 'Negrita', black: 'Negro' },
        cardBackText: 'REVERSO',
        cardBackOptions: { title: 'Estilo predeterminado', primaryColor: 'Color primario', secondaryColor: 'Color secundario', gradientType: 'Tipo de degradado', radial: 'Radial', linear: 'Lineal', angle: 'Ángulo', elements: 'Elementos decorativos', centerIcon: 'Icono central', cornerIcons: 'Iconos de esquina', frame: 'Marco', texture: 'Textura', border: 'Borde' }
    },
    de: {
        gifModal: {
            title: "📹 Hochwertige GIF-Aufnahme",
            body: "Für ein perfektes Ergebnis müssen wir den Bildschirm aufnehmen:",
            step1: "Wählen Sie die Option <strong>\"Tab\"</strong>.",
            step2: "Wählen Sie <strong>diese Seite</strong> aus der Liste.",
            step3: "Klicken Sie auf <strong>\"Teilen\"</strong>.",
            note: "Die Maus wird automatisch ausgeblendet und die Karte zugeschnitten.",
            warning: "Die Verwendung der maximalen Einstellungen (60 FPS / 4K) kann länger dauern und eine hohe CPU-Auslastung verursachen.",
            fpsLabel: "FPS",
            qualityLabel: "Qualität (Höhe)",
            fpsNormal: "15 FPS (Normal)",
            fpsCinema: "24 FPS (Kino)",
            fpsSmooth: "30 FPS (Flüssig)",
            fpsUltra: "60 FPS (Ultra)",
            qualitySD: "480p (SD)",
            qualityNormal: "720p (HD)",
            qualityHigh: "1080p (Full HD)",
            qualityQHD: "1440p (QHD)",
            qualityUltra: "4K (UHD)",
            cancel: "Abbrechen",
            start: "Aufnahme starten", loadingLibs: "⏳ Laden...", capturing: "📸 Aufnahme...", encoding: "⚙️ Kodierung..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'Erstellen Sie Ihre eigenen personalisierten Sammelkarten',
        hoverHint: '✨ Fahren Sie mit der Maus über die Karte, um den Effekt zu verstärken ✨',
        elements: { Fire: 'Feuer', Water: 'Wasser', Nature: 'Natur', Electric: 'Elektro', Mystic: 'Mystik', Fighting: 'Kampf', Shadow: 'Schatten', Metal: 'Metall', Light: 'Licht', Dragon: 'Drache', Ice: 'Eis', Neutral: 'Neutral' },
        effects: { none: { name: 'Keiner', description: 'Kein Effekt' }, holographic: { name: 'Holografisch', description: 'Klassischer Regenbogeneffekt' }, rainbow: { name: 'Regenbogen', description: 'Animierter mehrfarbiger Verlauf' }, gold: { name: 'Gold', description: 'Luxuriöse goldene Reflexionen' }, silver: { name: 'Silber', description: 'Metallische Silberreflexionen' }, prismatic: { name: 'Prismatisch', description: 'Brechender Kristalleffekt' }, neon: { name: 'Neon', description: 'Lebhaftes Neonleuchten' }, galaxy: { name: 'Galaxie', description: 'Sternenkosmischer Effekt' }, fire: { name: 'Flammen', description: 'Animierter Flammeneffekt' }, ice: { name: 'Frost', description: 'Funkelnder Eiseffekt' } },
        stages: ['Basis', 'Phase 1', 'Phase 2', 'Spezial', 'Legendär', 'Mythisch', 'Ultra'],
        rarities: { common: 'Gewöhnlich', uncommon: 'Ungewöhnlich', rare: 'Selten', epic: 'Episch', legendary: 'Legendär', mythic: 'Mythisch' },
        sections: { image: 'Bild', basicInfo: 'Grundinformationen', rarityEffects: 'Effekte', abilities: 'Fähigkeiten', stats: 'Statistiken', appearance: 'Aussehen', cardStyle: 'Kartenstil', textStyle: 'Textstil', particles: 'Partikel', abilityStyle: 'Fähigkeiten-Stil', reset: 'Zurücksetzen', cardBack: 'Kartenrückseite' },
        labels: { name: 'Name', hp: 'Lebenspunkte', element: 'Element', stage: 'Phase', description: 'Beschreibung', author: 'Autor', rarity: 'Seltenheit', effect: 'Effekt', weakness: 'Schwäche', resistance: 'Resistenz', retreatCost: 'Rückzugskosten', abilityName: 'Fähigkeitsname', damage: 'Schaden', energyCost: 'Energiekosten', abilityDesc: 'Fähigkeiten-Beschreibung', borderColor: 'Rahmenfarbe', backgroundColor: 'Kartenhintergrund', abilityBackground: 'Fähigkeitshintergrund', textColor: 'Textfarbe', font: 'Schriftart', size: 'Größe', weight: 'Dicke', zoom: 'Zoom', presets: 'Voreinstellungen', backgroundStyle: 'Hintergrundstil', solid: 'Einfarbig', gradient: 'Verlauf', cardInner: 'Karteninneres', primaryColor: 'Primärfarbe', secondaryColor: 'Sekundärfarbe', nameColor: 'Namensfarbe', hpColor: 'LP-Farbe', typeColor: 'Typfarbe', descColor: 'Beschreibungsfarbe', statsColor: 'Statistikfarbe', authorColor: 'Autorenfarbe', particleEmoji: 'Partikel-Emoji', animation: 'Animation', color: 'Farbe', stats: 'Stats', texture: 'Textur' },
        buttons: { addAbility: '+ Hinzufügen', remove: 'Entfernen', change: 'Ändern', recenter: 'Zentrieren', download: 'Herunterladen', autoRotate: '3D-Ansicht', resetCard: '🔄 Zurücksetzen', save: 'Speichern', load: 'Laden', deleteAll: 'Alle löschen', import: 'JSON importieren', storage: 'Speicher 💾', json: 'JSON', showFront: 'Vorderseite', flipCard: 'Umdrehen' },
        deckBuilder: { title: 'Deck-Builder', subtitle: 'A4 Druckbogen (9 Karten)', clear: 'Leeren', export: 'Bogen herunterladen', library: 'Bibliothek', full: 'Das Raster ist voll!', exporting: 'Vorbereitung...', success: 'Bogen heruntergeladen!', successPdf: 'PDF heruntergeladen!', error: 'Export fehlgeschlagen', errorLoad: 'Bibliothek konnte nicht geladen werden', clickToRemove: 'Klicken zum Entfernen', settings: 'Einstellungen', paperFormat: 'Format', cardCount: 'Karten', cardSize: 'Größe', presets: 'Schnellvorlagen', presetStandard: 'Standard', presetCompact: 'Kompakt', presetMini: 'Mini', presetMax: 'Max', cards: 'Karten', card: 'Karte', currentLayout: 'Layout', customize: 'Anpassen' },
        checkboxes: { showHP: 'Lebenspunkte anzeigen', showWeakRes: 'Schwäche/Resistenz anzeigen', showRetreat: 'Rückzugskosten anzeigen', showDescription: 'Beschreibung anzeigen', showTexture: 'Muster anzeigen', showParticles: 'Partikel anzeigen', showDamage: 'Schaden anzeigen' },
        imageEditor: { dropHint: 'Bild hier ablegen', orClick: 'oder klicken zum Auswählen', formats: 'PNG,JPG,GIF,WEBP (max 15MB)', loading: 'Laden...', unsupportedFormat: 'Nicht unterstütztes Format. Verwenden Sie PNG,JPG,GIF oder WEBP.', fileTooLarge: 'Datei zu groß. Maximal 15MB.', searchPlaceholder: 'Tippen...' },
        download: { title: '📥 Herunterladen', pngTitle: 'Transparentes PNG-Bild', jpgTitle: 'JPG-Bild mit Hintergrund', gifTitle: 'Animiertes GIF (3 Sekunden)', webpTitle: 'WebP-Bild', htmlTitle: 'Interaktive HTML-Datei', capturing: '⏳ Aufnahme...', encoding: '⚙️ Kodierung...', pngDesc: 'Hohe Qualität, transparent', jpgDesc: 'Kleine Größe, weißer Hintergrund', webpDesc: 'Für Web optimiert', gifDesc: 'Animierte Aufnahme (3s)', frontSide: 'Vorderseite', backSide: 'Rückseite', frontHint: 'Karte umdrehen für Rückseite', backHint: 'Karte umdrehen für Vorderseite', gifBackDisabled: 'GIF nur für Vorderseite verfügbar' },
        card: { hp: 'KP', weakness: 'Schwäche', resistance: 'Resistenz', cost: 'Kosten', illus: 'Illus.' },
        storage: { tabSave: 'Speichern', tabLoad: 'Laden' },
        json: { modalTitle: 'JSON Import / Export', importTitle: 'Karte importieren', exportTitle: 'Karte exportieren', importBtn: 'JSON-Datei importieren', exportBtn: 'JSON-Datei exportieren', help: 'Speichere deine Karte als .json-Datei.', successImport: 'Karte erfolgreich importiert!', errorImport: 'Ungültige JSON-Datei.' },
        defaults: { newAbility: 'Neue Fähigkeit', cardName: 'Meine Kreatur', description: 'Eine geheimnisvolle Kreatur mit unglaublichen Kräften.', author: 'Schöpfer', attackName1: 'Feuerball', attackDesc1: 'Wirf eine Münze. Bei Kopf ist das verteidigende Pokémon jetzt verbrannt.', attackName2: 'Flammenwurf', attackDesc2: 'Lege eine an dieses Pokémon angelegte Energie auf deinen Ablagestapel.' }, notifications: { success: 'Erfolg', error: 'Fehler', info: 'Information', warning: 'Warnung' },
        display: { title: 'Anzeigeoptionen' },
        tabs: { info: 'Info', content: 'Inhalt', visual: 'Visuell', style: 'Stil', colors: 'Farben' },
        common: { cancel: 'Abbrechen', close: 'Schließen', legalNotice: 'Impressum' },
        prompts: { resetConfirm: 'Alle Kartendaten zurücksetzen?', saveHint: 'Ihre Karte (Text + Bild) wird lokal gespeichert.', saveSuccess: 'Karte erfolgreich gespeichert!', loadConfirm: 'Diese Karte laden? Nicht gespeicherte Änderungen gehen verloren.', deleteConfirm: 'Diese gespeicherte Karte löschen?', deleteAllConfirm: 'Alle Karten löschen? Dies kann nicht rückgängig gemacht werden.', allDeleted: 'Alle Karten gelöscht', noSaves: 'Keine gespeicherten Karten gefunden.', quotaError: 'Speicher voll! Löschen Sie alte Karten.', saveError: 'Fehler beim Speichern der Karte.', autoDeleteInfo: 'Karten werden nach 30 Tagen gelöscht.' },
        textures: { none: 'Keine', grid: 'Gitter', scales: 'Schuppen', cross: 'Kreuz', stars: 'Sterne', hexagons: 'Sechsecke', lines: 'Linien', dots: 'Punkte', waves: 'Wellen', circuit: 'Schaltung' },
        animations: { fire: 'Aufsteigend', water: 'Blasen', nature: 'Schwebend', electric: 'Funken', mystic: 'Magie', fighting: 'Einschlag', shadow: 'Verblassen', metal: 'Zahnräder', light: 'Strahlen', dragon: 'Majestätisch', ice: 'Schnee', neutral: 'Subtil' },
        fontWeights: { normal: 'Normal', bold: 'Fett', black: 'Schwarz' },
        cardBackText: 'KARTENRÜCKSEITE',
        cardBackOptions: { title: 'Standard-Stil', primaryColor: 'Primärfarbe', secondaryColor: 'Sekundärfarbe', gradientType: 'Verlaufstyp', radial: 'Radial', linear: 'Linear', angle: 'Winkel', elements: 'Dekorative Elemente', centerIcon: 'Zentrales Symbol', cornerIcons: 'Ecksymbole', frame: 'Rahmen', texture: 'Textura', border: 'Rand' }
    },

    ru: {
        gifModal: {
            title: "📹 Высококачественная GIF-съемка",
            body: "Для идеального результата нам нужно захватить экран:",
            step1: "Выберите опцию <strong>\"Вкладка\"</strong>.",
            step2: "Выберите <strong>эту страницу</strong> из списка.",
            step3: "Нажмите <strong>\"Поделиться\"</strong>.",
            note: "Мышь будет автоматически скрыта, а карта обрезана.",
            warning: "Использование максимальных настроек (60 FPS / 4K) может занять больше времени и использовать много ресурсов ЦП.",
            fpsLabel: "FPS",
            qualityLabel: "Качество (Высота)",
            fpsNormal: "15 FPS (Нормально)",
            fpsCinema: "24 FPS (Кино)",
            fpsSmooth: "30 FPS (Плавнo)",
            fpsUltra: "60 FPS (Ультра)",
            qualitySD: "480p (SD)",
            qualityNormal: "720p (HD)",
            qualityHigh: "1080p (Full HD)",
            qualityQHD: "1440p (QHD)",
            qualityUltra: "4K (UHD)",
            cancel: "Отмена",
            start: "Начать захват", loadingLibs: "⏳ Загрузка...", capturing: "📸 Захват...", encoding: "⚙️ Кодирование..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'Создавайте свои собственные коллекционные карты',
        hoverHint: '✨ Наведите на карту, чтобы усилить эффект ✨',
        elements: { Fire: 'Огонь', Water: 'Вода', Nature: 'Природа', Electric: 'Электричество', Mystic: 'Мистика', Fighting: 'Боевой', Shadow: 'Тень', Metal: 'Металл', Light: 'Свет', Dragon: 'Дракон', Ice: 'Лёд', Neutral: 'Нейтральный' },
        effects: { none: { name: 'Нет', description: 'Без эффекта' }, holographic: { name: 'Голографический', description: 'Классический радужный эффект' }, rainbow: { name: 'Радуга', description: 'Анимированный многоцветный градиент' }, gold: { name: 'Золото', description: 'Роскошные золотые отражения' }, silver: { name: 'Серебро', description: 'Металлические серебряные отражения' }, prismatic: { name: 'Призматический', description: 'Эффект преломляющего кристалла' }, neon: { name: 'Неон', description: 'Яркое неоновое свечение' }, galaxy: { name: 'Галактика', description: 'Звёздный космический эффект' }, fire: { name: 'Пламя', description: 'Анимированный эффект огня' }, ice: { name: 'Лёд', description: 'Сверкающий ледяной эффект' } },
        stages: ['Базовый', 'Стадия 1', 'Стадия 2', 'Особый', 'Легендарный', 'Мифический', 'Ультра'],
        rarities: { common: 'Обычная', uncommon: 'Необычная', rare: 'Редкая', epic: 'Эпическая', legendary: 'Легендарная', mythic: 'Мифическая' },
        sections: { image: 'Изображение', basicInfo: 'Основная информация', rarityEffects: 'Эффекты', abilities: 'Способности', stats: 'Характеристики', appearance: 'Внешний вид', cardStyle: 'Стиль карты', textStyle: 'Стиль текста', particles: 'Частицы', abilityStyle: 'Стиль способностей', reset: 'Сброс', cardBack: 'Обратная сторона' },
        labels: { name: 'Имя', hp: 'Очки здоровья', element: 'Элемент', stage: 'Стадия', description: 'Описание', author: 'Автор', rarity: 'Редкость', effect: 'Эффект', weakness: 'Слабость', resistance: 'Сопротивление', retreatCost: 'Стоимость отступления', abilityName: 'Название способности', damage: 'Урон', energyCost: 'Стоимость энергии', abilityDesc: 'Описание способностей', borderColor: 'Цвет рамки', backgroundColor: 'Фон карты', abilityBackground: 'Фон способности', textColor: 'Цвет текста', font: 'Шрифт', size: 'Размер', weight: 'Вес', zoom: 'Масштаб', presets: 'Предустановки', backgroundStyle: 'Стиль фона', solid: 'Сплошной', gradient: 'Градиент', cardInner: 'Внутренняя часть карты', primaryColor: 'Основной цвет', secondaryColor: 'Вторичный цвет', nameColor: 'Цвет имени', hpColor: 'Цвет ОЗ', typeColor: 'Цвет типа', descColor: 'Цвет описания', statsColor: 'Цвет хар-к', authorColor: 'Цвет автора', particleEmoji: 'Эмодзи частиц', animation: 'Анимация', color: 'Цвет', stats: 'Хар-ки', texture: 'Текстура' },
        buttons: { addAbility: '+ Добавить', remove: 'Удалить', change: 'Изменить', recenter: 'Центрировать', download: 'Скачать', autoRotate: '3D-вид', resetCard: '🔄 Сброс', save: 'Сохранить', load: 'Загрузить', deleteAll: 'Удалить все', import: 'Импорт JSON', storage: 'Сохранение 💾', json: 'JSON', showFront: 'Лицевая', flipCard: 'Перевернуть' },
        deckBuilder: { title: 'Конструктор колоды', subtitle: 'Лист A4 (9 карт)', clear: 'Очистить', export: 'Скачать лист', library: 'Библиотека', full: 'Сетка заполнена!', exporting: 'Подготовка...', success: 'Лист скачан!', successPdf: 'PDF скачан!', error: 'Ошибка экспорта', errorLoad: 'Не удалось загрузить библиотеку', clickToRemove: 'Нажмите для удаления', settings: 'Настройки', paperFormat: 'Формат', cardCount: 'Карты', cardSize: 'Размер', presets: 'Быстрые шаблоны', presetStandard: 'Стандарт', presetCompact: 'Компакт', presetMini: 'Мини', presetMax: 'Макс', cards: 'карт', card: 'карта', currentLayout: 'Раскладка', customize: 'Настроить' },
        checkboxes: { showHP: 'Показать очки здоровья', showWeakRes: 'Показать слабость/сопротивление', showRetreat: 'Показать стоимость отступления', showDescription: 'Показать описание', showTexture: 'Показать текстуру', showParticles: 'Показать частицы', showDamage: 'Показать урон' },
        imageEditor: { dropHint: 'Перетащите изображение сюда', orClick: 'или нажмите для выбора', formats: 'PNG,JPG,GIF,WEBP (макс 15МБ)', loading: 'Загрузка...', unsupportedFormat: 'Неподдерживаемый формат. Используйте PNG,JPG,GIF или WEBP.', fileTooLarge: 'Файл слишком большой. Максимум 15МБ.', searchPlaceholder: 'Введите...' },
        download: { title: '📥 Скачать', pngTitle: 'Прозрачное PNG изображение', jpgTitle: 'JPG изображение с фоном', gifTitle: 'Анимированный GIF (3 секунды)', webpTitle: 'WebP изображение', htmlTitle: 'Интерактивный HTML файл', capturing: '⏳ Захват...', encoding: '⚙️ Кодирование...', pngDesc: 'Высокое качество, прозрачный', jpgDesc: 'Маленький размер, белый фон', webpDesc: 'Оптимизирован для веб', gifDesc: 'Анимированный захват (3с)', frontSide: 'Лицевая сторона', backSide: 'Обратная сторона', frontHint: 'Переверните карту для скачивания задней стороны', backHint: 'Переверните карту для скачивания лицевой стороны', gifBackDisabled: 'GIF доступен только для лицевой стороны' },
        card: { hp: 'ОЗ', weakness: 'Слабость', resistance: 'Сопротивление', cost: 'Стоимость', illus: 'Худ.' },
        storage: { tabSave: 'Сохранить', tabLoad: 'Загрузить' },
        json: { modalTitle: 'Импорт / Экспорт JSON', importTitle: 'Импорт карты', exportTitle: 'Экспорт карты', importBtn: 'Импорт файла JSON', exportBtn: 'Экспорт файла JSON', help: 'Сохраните карту как .json файл.', successImport: 'Карта импортирована!', errorImport: 'Неверный JSON.' },
        defaults: { newAbility: 'Новая способность', cardName: 'Моё Существо', description: 'Таинственное существо с невероятными силами.', author: 'Создатель', attackName1: 'Огненный шар', attackDesc1: 'Подбросьте монету. Если выпадет орел, Защищающийся покемон теперь обожжен.', attackName2: 'Огнемет', attackDesc2: 'Сбросьте Энергию, прикрепленную к этому покемону.' }, notifications: { success: 'Успех', error: 'Ошибка', info: 'Информация', warning: 'Предупреждение' },
        display: { title: 'Параметры отображения' },
        tabs: { info: 'Инфо', content: 'Содержание', visual: 'Визуал', style: 'Стиль', colors: 'Цвета' },
        common: { cancel: 'Отмена', close: 'Закрыть', legalNotice: 'Правовая информация' },
        prompts: { resetConfirm: 'Сбросить все данные карты?', saveHint: 'Ваша карта (текст + изображение) будет сохранена локально.', saveSuccess: 'Карта успешно сохранена!', loadConfirm: 'Загрузить эту карту? Несохранённые изменения будут потеряны.', deleteConfirm: 'Удалить эту сохранённую карту?', deleteAllConfirm: 'Удалить все карты? Это действие нельзя отменить.', allDeleted: 'Все карты удалены', noSaves: 'Сохранённые карты не найдены.', quotaError: 'Хранилище заполнено! Удалите старые карты.', saveError: 'Ошибка сохранения карты.', autoDeleteInfo: 'Карты удаляются через 30 дней.' },
        textures: { none: 'Нет', grid: 'Сетка', scales: 'Чешуя', cross: 'Крест', stars: 'Звезды', hexagons: 'Шестиугольники', lines: 'Линии', dots: 'Точки', waves: 'Волны', circuit: 'Схема' },
        animations: { fire: 'Восходящий', water: 'Пузыри', nature: 'Парящий', electric: 'Искры', mystic: 'Магия', fighting: 'Удар', shadow: 'Затухание', metal: 'Шестеренки', light: 'Сияние', dragon: 'Величественный', ice: 'Снег', neutral: 'Тонкий' },
        fontWeights: { normal: 'Обычный', bold: 'Жирный', black: 'Чёрный' },
        cardBackText: 'ОБРАТНАЯ СТОРОНА',
        cardBackOptions: { title: 'Стиль по умолчанию', primaryColor: 'Основной цвет', secondaryColor: 'Вторичный цвет', gradientType: 'Тип градиента', radial: 'Радиальный', linear: 'Линейный', angle: 'Угол', elements: 'Декоративные элементы', centerIcon: 'Центральный значок', cornerIcons: 'Угловые значки', frame: 'Рамка', texture: 'Текстура', border: 'Граница' }
    },
    ja: {
        gifModal: {
            title: "📹 高品質GIFキャプチャ",
            body: "完璧な結果を得るために、画面をキャプチャする必要があります：",
            step1: "<strong>「タブ」</strong>オプションを選択します。",
            step2: "リストから<strong>このページ</strong>を選択します。",
            step3: "<strong>「共有」</strong>をクリックします。",
            note: "マウスは自動的に非表示になり、カードは切り取られます。",
            warning: "最大設定（60 FPS / 4K）を使用すると、時間がかかり、CPU使用率が高くなる可能性があります。",
            fpsLabel: "FPS",
            qualityLabel: "品質 (高さ)",
            fpsNormal: "15 FPS (通常)",
            fpsCinema: "24 FPS (シネマ)",
            fpsSmooth: "30 FPS (スムーズ)",
            fpsUltra: "60 FPS (ウルトラ)",
            qualitySD: "480p (標準)",
            qualityNormal: "720p (高画質)",
            qualityHigh: "1080p (フルHD)",
            qualityQHD: "1440p (2K)",
            qualityUltra: "4K (超高画質)",
            cancel: "キャンセル",
            start: "キャプチャ開始", loadingLibs: "⏳ 読み込み中...", capturing: "📸 キャプチャ中...", encoding: "⚙️ エンコード中..."
        },
        appTitle: 'Card Creator',
        appSubtitle: 'オリジナルのコレクションカードを作成しよう',
        hoverHint: '✨ カードにマウスを乗せるとエフェクトが強くなります ✨',
        elements: { Fire: '炎', Water: '水', Nature: '自然', Electric: '電気', Mystic: '神秘', Fighting: '格闘', Shadow: '闇', Metal: '鋼', Light: '光', Dragon: 'ドラゴン', Ice: '氷', Neutral: '無' },
        effects: { none: { name: 'なし', description: 'エフェクトなし' }, holographic: { name: 'ホログラフィック', description: 'クラシックな虹色エフェクト' }, rainbow: { name: 'レインボー', description: 'アニメーションカラーグラデーション' }, gold: { name: 'ゴールド', description: '豪華な金色の反射' }, silver: { name: 'シルバー', description: 'メタリックな銀色の反射' }, prismatic: { name: 'プリズマティック', description: '屈折するクリスタルエフェクト' }, neon: { name: 'ネオン', description: '鮮やかなネオンの輝き' }, galaxy: { name: 'ギャラクシー', description: '星空の宇宙エフェクト' }, fire: { name: 'フレイム', description: 'アニメーション炎エフェクト' }, ice: { name: 'フロスト', description: 'きらめく氷エフェクト' } },
        stages: ['ベーシック', 'ステージ1', 'ステージ2', 'スペシャル', 'レジェンダリー', 'ミシック', 'ウルトラ'],
        rarities: { common: 'コモン', uncommon: 'アンコモン', rare: 'レア', epic: 'エピック', legendary: 'レジェンダリー', mythic: 'ミシック' },
        sections: { image: '画像', basicInfo: '基本情報', rarityEffects: 'エフェクト', abilities: '技', stats: 'ステータス', appearance: '外観', cardStyle: 'カードスタイル', textStyle: 'テキストスタイル', particles: 'パーティクル', abilityStyle: '技のスタイル', reset: 'リセット', cardBack: 'カード裏面' },
        labels: { name: '名前', hp: 'HP', element: 'タイプ', stage: 'ステージ', description: '説明', author: '作者', rarity: 'レアリティ', effect: 'エフェクト', weakness: '弱点', resistance: '抵抗力', retreatCost: 'にげるコスト', abilityName: '技名', damage: 'ダメージ', energyCost: 'エネルギーコスト', abilityDesc: '技の説明', borderColor: '枠の色', backgroundColor: 'カードの背景', abilityBackground: '技の背景', textColor: '文字色', font: 'フォント', size: 'サイズ', weight: '太さ', zoom: 'ズーム', presets: 'プリセット', backgroundStyle: '背景スタイル', solid: '単色', gradient: 'グラデーション', cardInner: 'カード内側', primaryColor: 'メインカラー', secondaryColor: 'サブカラー', nameColor: '名前の色', hpColor: 'HPの色', typeColor: 'タイプの色', descColor: '説明の色', statsColor: 'ステータスの色', authorColor: '作者の色', particleEmoji: 'パーティクル絵文字', animation: 'アニメーション', color: '色', stats: 'ステータス', texture: 'テクスチャ' },
        buttons: { addAbility: '+ 追加', remove: '削除', change: '変更', recenter: '中央揃え', download: 'ダウンロード', autoRotate: '3Dビュー', resetCard: '🔄 リセット', save: '保存', load: '読み込み', deleteAll: 'すべて削除', import: 'JSONをインポート', storage: '保存データ 💾', json: 'JSON', showFront: '表面', flipCard: '裏返す' },
        deckBuilder: { title: 'デッキビルダー', subtitle: 'A4印刷シート（9枚）', clear: 'クリア', export: 'シートをダウンロード', library: 'ライブラリ', full: 'グリッドがいっぱいです！', exporting: '準備中...', success: 'シートをダウンロードしました！', successPdf: 'PDFをダウンロードしました！', error: 'エクスポートに失敗', errorLoad: 'ライブラリを読み込めませんでした', clickToRemove: 'クリックして削除', settings: '設定', paperFormat: '用紙', cardCount: '枚数', cardSize: 'サイズ', presets: 'クイックプリセット', presetStandard: 'スタンダード', presetCompact: 'コンパクト', presetMini: 'ミニ', presetMax: '最大', cards: '枚', card: '枚', currentLayout: 'レイアウト', customize: 'カスタマイズ' },
        checkboxes: { showHP: 'HPを表示', showWeakRes: '弱点/抵抗力を表示', showRetreat: 'にげるコストを表示', showDescription: '説明を表示', showTexture: 'テクスチャを表示', showParticles: 'パーティクルを表示', showDamage: 'ダメージを表示' },
        imageEditor: { dropHint: 'ここに画像をドロップ', orClick: 'またはクリックして選択', formats: 'PNG,JPG,GIF,WEBP (最大15MB)', loading: '読み込み中...', unsupportedFormat: 'サポートされていない形式です。PNG、JPG、GIF、WEBPを使用してください。', fileTooLarge: 'ファイルが大きすぎます。最大15MBです。', searchPlaceholder: '入力...' },
        download: { title: '📥 ダウンロード', pngTitle: '透過PNG画像', jpgTitle: '背景付きJPG画像', gifTitle: 'アニメーションGIF（3秒）', webpTitle: 'WebP画像', htmlTitle: 'インタラクティブHTMLファイル', capturing: '⏳ キャプチャ中...', encoding: '⚙️ エンコード中...', pngDesc: '高画質、透過', jpgDesc: '軽量、白背景', webpDesc: 'ウェブ最適化', gifDesc: 'アニメーション (3秒)', frontSide: '表面', backSide: '裏面', frontHint: 'カードを裏返して裏面をダウンロード', backHint: 'カードを裏返して表面をダウンロード', gifBackDisabled: 'GIFは表面のみ利用可能' },
        card: { hp: 'HP', weakness: '弱点', resistance: '抵抗力', cost: 'コスト', illus: 'イラスト' },
        storage: { tabSave: '保存', tabLoad: '読み込み' },
        json: { modalTitle: 'JSON インポート / エクスポート', importTitle: 'カードをインポート', exportTitle: 'カードをエクスポート', importBtn: 'JSONファイルをインポート', exportBtn: 'JSONファイルをエクスポート', help: '.jsonファイルとして保存し、後で復元できます。', successImport: 'インポート完了！', errorImport: '無効なJSONです。' },
        defaults: { newAbility: '新しい技', cardName: 'マイ・クリーチャー', description: '信じられないほどの力を持つ神秘的な生き物。', author: 'クリエイター', attackName1: '火の玉', attackDesc1: 'コインを1回投げる。オモテなら、相手のバトルポケモンをやけどにする。', attackName2: 'かえんほうしゃ', attackDesc2: 'このポケモンについているエネルギーを1個選び、トラッシュする。' }, notifications: { success: '成功', error: 'エラー', info: '情報', warning: '警告' },
        display: { title: '表示オプション' },
        tabs: { info: '情報', content: 'コンテンツ', visual: 'ビジュアル', style: 'スタイル', colors: '色' },
        common: { cancel: 'キャンセル', close: '閉じる', legalNotice: '利用規約' },
        prompts: { resetConfirm: 'すべてのカードデータをリセットしますか？', saveHint: 'カード（テキスト + 画像）がローカルに保存されます。', saveSuccess: 'カードが正常に保存されました！', loadConfirm: 'このカードを読み込みますか？未保存の変更は失われます。', deleteConfirm: 'この保存済みカードを削除しますか？', deleteAllConfirm: 'すべてのカードを削除しますか？この操作は元に戻せません。', allDeleted: 'すべてのカードが削除されました', noSaves: '保存済みカードが見つかりません。', quotaError: 'ストレージがいっぱいです！古いカードを削除してください。', saveError: 'カードの保存中にエラーが発生しました。', autoDeleteInfo: '保存されたカードは30日後に削除されます。' },
        textures: { none: 'なし', grid: 'グリッド', scales: '鱗', cross: 'クロス', stars: '星', hexagons: 'ヘキサゴン', lines: 'ライン', dots: 'ドット', waves: 'ウェーブ', circuit: '回路' },
        animations: { fire: '上昇', water: '泡', nature: '浮遊', electric: '火花', mystic: '魔法', fighting: '衝撃', shadow: 'フェード', metal: '歯車', light: '放射', dragon: '威厳', ice: '雪', neutral: '微細' },
        fontWeights: { normal: '標準', bold: '太字', black: '極太' },
        cardBackText: 'カード裏面',
        cardBackOptions: { title: 'デフォルトスタイル', primaryColor: 'メインカラー', secondaryColor: 'サブカラー', gradientType: 'グラデーションタイプ', radial: '放射状', linear: '線形', angle: '角度', elements: '装飾要素', centerIcon: '中央アイコン', cornerIcons: '角アイコン', frame: 'フレーム', texture: 'テクスチャ', border: '境界線' }
    },
    zh: {
        gifModal: {
            title: "📹 高质量GIF捕获",
            body: "为了获得完美的效果，我们需要捕获屏幕：",
            step1: "选择 <strong>「标签页」</strong> 选项。",
            step2: "从列表中选择 <strong>此页面</strong>。",
            step3: "点击 <strong>「分享」</strong>。",
            note: "鼠标将自动隐藏，卡片将被裁剪。",
            warning: "使用最大设置（60 FPS / 4K）可能需要更长时间并占用大量CPU。",
            fpsLabel: "FPS",
            qualityLabel: "质量 (高度)",
            fpsNormal: "15 FPS (正常)",
            fpsCinema: "24 FPS (电影)",
            fpsSmooth: "30 FPS (流畅)",
            fpsUltra: "60 FPS (超高)",
            qualitySD: "480p (标清)",
            qualityNormal: "720p (高清)",
            qualityHigh: "1080p (全高清)",
            qualityQHD: "1440p (2K超清)",
            qualityUltra: "4K (超高清)",
            cancel: "取消",
            start: "开始捕获", loadingLibs: "⏳ 加载中...", capturing: "📸 捕获中...", encoding: "⚙️ 编码中..."
        },
        appTitle: 'Card Creator',
        appSubtitle: '创建您自己的个性化收藏卡',
        hoverHint: '✨ 将鼠标悬停在卡片上以增强效果 ✨',
        elements: { Fire: '火', Water: '水', Nature: '自然', Electric: '电', Mystic: '神秘', Fighting: '格斗', Shadow: '暗', Metal: '钢', Light: '光', Dragon: '龙', Ice: '冰', Neutral: '无' },
        effects: { none: { name: '无', description: '无效果' }, holographic: { name: '全息', description: '经典彩虹效果' }, rainbow: { name: '彩虹', description: '动画多色渐变' }, gold: { name: '金色', description: '奢华金色反射' }, silver: { name: '银色', description: '金属银色反射' }, prismatic: { name: '棱镜', description: '折射水晶效果' }, neon: { name: '霓虹', description: '鲜艳霓虹光芒' }, galaxy: { name: '星系', description: '星空宇宙效果' }, fire: { name: '火焰', description: '动画火焰效果' }, ice: { name: '冰霜', description: '闪烁冰晶效果' } },
        stages: ['基础', '阶段1', '阶段2', '特殊', '传说', '神话', '究极'],
        rarities: { common: '普通', uncommon: '稀有', rare: '珍贵', epic: '史诗', legendary: '传说', mythic: '神话' },
        sections: { image: '图片', basicInfo: '基本信息', rarityEffects: '效果', abilities: '技能', stats: '属性', appearance: '外观', cardStyle: '卡片样式', textStyle: '文本样式', particles: '粒子系统', abilityStyle: '技能样式', reset: '重置', cardBack: '卡片背面' },
        labels: { name: '名称', hp: '生命值', element: '属性', stage: '阶段', description: '描述', author: '作者', rarity: '稀有度', effect: '效果', weakness: '弱点', resistance: '抗性', retreatCost: '撤退消耗', abilityName: '技能名称', damage: '伤害', energyCost: '能量消耗', abilityDesc: '技能描述', borderColor: '边框颜色', backgroundColor: '卡片背景', abilityBackground: '技能背景', textColor: '文字颜色', font: '字体', size: '大小', weight: '粗细', zoom: '缩放', backgroundStyle: '背景样式', solid: '纯色', gradient: '渐变', cardInner: '卡片内部', primaryColor: '主色', secondaryColor: '副色', presets: '预设', nameColor: '名称颜色', hpColor: '生命值颜色', typeColor: '属性颜色', descColor: '描述颜色', statsColor: '属性颜色', authorColor: '作者颜色', particleEmoji: '粒子表情', animation: '动画', color: '颜色', stats: '属性', texture: '纹理' },
        buttons: { addAbility: '+ 添加', remove: '删除', change: '更改', recenter: '居中', download: '下载', autoRotate: '3D视图', resetCard: '🔄 重置', save: '保存', load: '加载', deleteAll: '全部删除', import: '导入 JSON', storage: '存档 💾', json: 'JSON', showFront: '显示正面', flipCard: '翻转卡牌' },
        deckBuilder: { title: '牌组构建器', subtitle: 'A4打印纸（9张卡）', clear: '清空', export: '下载卡片表', library: '卡牌库', full: '网格已满！', exporting: '准备中...', success: '表格已下载！', successPdf: 'PDF已下载！', error: '导出失败', errorLoad: '无法加载卡牌库', clickToRemove: '点击移除', settings: '设置', paperFormat: '纸张', cardCount: '数量', cardSize: '大小', presets: '快速预设', presetStandard: '标准', presetCompact: '紧凑', presetMini: '迷你', presetMax: '最大', cards: '张', card: '张', currentLayout: '布局', customize: '自定义' },
        checkboxes: { showHP: '显示生命值', showWeakRes: '显示弱点/抗性', showRetreat: '显示撤退消耗', showDescription: '显示描述', showTexture: '显示纹理', showParticles: '显示粒子', showDamage: '显示伤害' },
        imageEditor: { dropHint: '将图片拖放到这里', orClick: '或点击选择', formats: 'PNG,JPG,GIF,WEBP (最大15MB)', loading: '加载中...', unsupportedFormat: '不支持的格式。请使用PNG、JPG、GIF或WEBP。', fileTooLarge: '文件太大。最大15MB。', searchPlaceholder: '输入...' },
        download: { title: '📥 下载', pngTitle: '透明PNG图片', jpgTitle: '带背景的JPG图片', gifTitle: '动画GIF（3秒）', webpTitle: 'WebP图片', htmlTitle: '交互式HTML文件', capturing: '⏳ 捕获中...', encoding: '⚙️ 编码中...', pngDesc: '高质量，透明', jpgDesc: '小尺寸，白色背景', webpDesc: '网页优化', gifDesc: '动画捕获 (3秒)', frontSide: '正面', backSide: '背面', frontHint: '翻转卡片以下载背面', backHint: '翻转卡片以下载正面', gifBackDisabled: 'GIF仅适用于正面' },
        card: { hp: 'HP', weakness: '弱点', resistance: '抗性', cost: '消耗', illus: '画师' },
        storage: { tabSave: '保存', tabLoad: '加载' },
        json: { modalTitle: 'JSON 导入 / 导出', importTitle: '导入卡片', exportTitle: '导出卡片', importBtn: '导入 JSON 文件', exportBtn: '导出 JSON 文件', help: '将卡片保存为 .json 文件。', successImport: '卡片导入成功！', errorImport: '无效的 JSON 文件。' },
        defaults: { newAbility: '新技能', cardName: '我的生物', description: '具有不可思议力量的神秘生物。', author: '创作者', attackName1: '火球', attackDesc1: '投掷硬币。如果是正面，防守宝可梦现在被烧伤。', attackName2: '喷射火焰', attackDesc2: '丢弃该宝可梦身上的一个能量。' }, notifications: { success: '成功', error: '错误', info: '信息', warning: '警告' },
        display: { title: '显示选项' },
        tabs: { info: '信息', content: '内容', visual: '视觉', style: '样式', colors: '颜色' },
        common: { cancel: '取消', close: '关闭', legalNotice: '法律声明' },
        prompts: { resetConfirm: '重置所有卡片数据？', saveHint: '您的卡片（文字 + 图片）将保存在本地。', saveSuccess: '卡片保存成功！', loadConfirm: '加载此卡片？未保存的更改将丢失。', deleteConfirm: '删除此已保存的卡片？', deleteAllConfirm: '删除所有卡片？此操作无法撤销。', allDeleted: '所有卡片已删除', noSaves: '未找到已保存的卡片。', quotaError: '存储空间已满！请删除旧卡片。', saveError: '保存卡片时出错。', autoDeleteInfo: '卡片将在30天后自动删除。' },
        textures: { none: '无', grid: '网格', scales: '鳞片', cross: '十字', stars: '星星', hexagons: '六边形', lines: '线条', dots: '点阵', waves: '波浪', circuit: '电路' },
        animations: { fire: '上升', water: '气泡', nature: '漂浮', electric: '火花', mystic: '魔法', fighting: '冲击', shadow: '淡入淡出', metal: '齿轮', light: '辐射', dragon: '威严', ice: '雪', neutral: '微妙' },
        fontWeights: { normal: '常规', bold: '粗体', black: '黑体' },
        cardBackText: '卡片背面',
        cardBackOptions: { title: '默认样式', primaryColor: '主色', secondaryColor: '副色', gradientType: '渐变类型', radial: '径向', linear: '线性', angle: '角度', elements: '装饰元素', centerIcon: '中心图标', cornerIcons: '角落图标', frame: '边框', texture: '纹理', border: '边界' }
    },
};

// Card Limits
const CARD_LIMITS = {
    HP_MIN: 0, HP_MAX: 999, DAMAGE_MIN: 0, DAMAGE_MAX: 9999, COST_MIN: 0, COST_MAX: 6, RETREAT_MIN: 0, RETREAT_MAX: 5, NAME_MAX_LENGTH: 25, DESC_MAX_LENGTH: 150, ATTACK_DESC_MAX_LENGTH: 80, AUTHOR_MAX_LENGTH: 30, MAX_FILE_SIZE: 25 * 1024 * 1024, // 25MB
    ZOOM_MIN: 1, ZOOM_MAX: 3,
};

// Element Types
const ELEMENT_TYPES = {
    Fire: { icon: '🔥', primary: '#FF6B35', secondary: '#FFE066', weakness: '💧', resistance: '🌿' },
    Water: { icon: '💧', primary: '#4FC3F7', secondary: '#E1F5FE', weakness: '⚡', resistance: '🔥' },
    Nature: { icon: '🌿', primary: '#66BB6A', secondary: '#C8E6C9', weakness: '🔥', resistance: '💧' },
    Electric: { icon: '⚡', primary: '#FFEE58', secondary: '#FFF9C4', weakness: '👊', resistance: '⚙️' },
    Mystic: { icon: '🔮', primary: '#BA68C8', secondary: '#F3E5F5', weakness: '🌑', resistance: '👊' },
    Fighting: { icon: '👊', primary: '#D84315', secondary: '#FFAB91', weakness: '🔮', resistance: '🌑' },
    Shadow: { icon: '🌑', primary: '#5D4037', secondary: '#A1887F', weakness: '✨', resistance: '🔮' },
    Metal: { icon: '⚙️', primary: '#90A4AE', secondary: '#ECEFF1', weakness: '🔥', resistance: '🌿' },
    Light: { icon: '✨', primary: '#FFD54F', secondary: '#FFF8E1', weakness: '🌑', resistance: '🔮' },
    Dragon: { icon: '🐉', primary: '#7E57C2', secondary: '#D1C4E9', weakness: '❄️', resistance: '🔥' },
    Ice: { icon: '❄️', primary: '#4DD0E1', secondary: '#E0F7FA', weakness: '🔥', resistance: '💧' },
    Neutral: { icon: '⭐', primary: '#BDBDBD', secondary: '#F5F5F5', weakness: '👊', resistance: '👻' },
};
const ELEMENT_KEYS = Object.keys(ELEMENT_TYPES);

const STAGES = ['Base', 'Stage1', 'Stage2', 'Special', 'Legendary', 'Mythic', 'Ultra'];

const ELEMENT_TEXTURES = {
    Fire: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 5c-5 10-15 15-15 25 0 8 7 15 15 15s15-7 15-15c0-10-10-15-15-25z' fill='%23ff6b3520' /%3E%3Cpath d='M30 15c-3 6-9 9-9 15 0 5 4 9 9 9s9-4 9-9c0-6-6-9-9-15z' fill='%23ff450015' /%3E%3C/svg%3E")`, Water: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='15' cy='15' r='8' fill='%2300bcd420' /%3E%3Ccircle cx='45' cy='35' r='6' fill='%232196f315' /%3E%3Ccircle cx='25' cy='45' r='10' fill='%2303a9f418' /%3E%3Cpath d='M5 30 Q15 25 25 30 T45 30 T60 30' stroke='%2300bcd415' fill='none' stroke-width='2'/%3E%3C/svg%3E")`, Nature: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 5 Q35 15 30 25 Q25 15 30 5z' fill='%234caf5020' /%3E%3Cpath d='M15 30 Q25 35 20 45 Q15 35 15 30z' fill='%238bc34a18' /%3E%3Cpath d='M45 25 Q50 35 45 45 Q40 35 45 25z' fill='%234caf5015' /%3E%3Ccircle cx='10' cy='50' r='3' fill='%234caf5012' /%3E%3C/svg%3E")`, Electric: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 0 L25 25 L35 20 L20 60 L25 30 L15 35 Z' fill='%23ffeb3b15' /%3E%3Cpath d='M50 10 L48 20 L52 18 L45 35' stroke='%23ffc10710' fill='none' stroke-width='2'/%3E%3Ccircle cx='10' cy='45' r='2' fill='%23ffeb3b20' /%3E%3C/svg%3E")`, Mystic: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpolygon points='30,5 32,15 40,10 35,18 45,20 35,22 40,30 32,25 30,35 28,25 20,30 25,22 15,20 25,18 20,10 28,15' fill='%239c27b015' /%3E%3Ccircle cx='10' cy='50' r='4' fill='%23e91e6310' /%3E%3Ccircle cx='50' cy='45' r='3' fill='%239c27b012' /%3E%3C/svg%3E")`, Fighting: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10 10 L50 50' stroke='%23f4433615' stroke-width='4' stroke-linecap='round'/%3E%3Cpath d='M50 10 L10 50' stroke='%23ff572215' stroke-width='4' stroke-linecap='round'/%3E%3Cpath d='M30 5 L30 55' stroke='%23f4433610' stroke-width='3'/%3E%3Cpath d='M5 30 L55 30' stroke='%23f4433610' stroke-width='3'/%3E%3C/svg%3E")`, Shadow: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cellipse cx='30' cy='50' rx='20' ry='8' fill='%2300000015' /%3E%3Cellipse cx='15' cy='30' rx='10' ry='5' fill='%2300000010' /%3E%3Cellipse cx='45' cy='20' rx='12' ry='6' fill='%2300000012' /%3E%3Cpath d='M20 10 Q30 20 25 35 Q35 25 40 40' stroke='%2300000008' fill='none' stroke-width='3'/%3E%3C/svg%3E")`, Metal: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Crect x='5' y='5' width='20' height='20' rx='2' fill='none' stroke='%2360606015' stroke-width='2'/%3E%3Crect x='35' y='35' width='20' height='20' rx='2' fill='none' stroke='%2360606015' stroke-width='2'/%3E%3Ccircle cx='15' cy='15' r='3' fill='%2390909020' /%3E%3Ccircle cx='45' cy='45' r='3' fill='%2390909020' /%3E%3Ccircle cx='45' cy='15' r='2' fill='%2360606015' /%3E%3Ccircle cx='15' cy='45' r='2' fill='%2360606015' /%3E%3C/svg%3E")`, Light: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='30' cy='30' r='15' fill='%23fff59d10' /%3E%3Cpath d='M30 5 L30 15 M30 45 L30 55 M5 30 L15 30 M45 30 L55 30 M12 12 L19 19 M41 41 L48 48 M12 48 L19 41 M41 19 L48 12' stroke='%23ffeb3b15' stroke-width='2' stroke-linecap='round'/%3E%3C/svg%3E")`, Dragon: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10 20 Q20 15 30 20 Q40 15 50 20 L50 35 Q40 40 30 35 Q20 40 10 35 Z' fill='%23673ab720' /%3E%3Cpath d='M10 35 Q20 30 30 35 Q40 30 50 35 L50 50 Q40 55 30 50 Q20 55 10 50 Z' fill='%23673ab715' /%3E%3Cpath d='M10 5 Q20 0 30 5 Q40 0 50 5 L50 20 Q40 25 30 20 Q20 25 10 20 Z' fill='%23673ab712' /%3E%3C/svg%3E")`, Ice: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 5 L30 55 M15 15 L45 45 M45 15 L15 45' stroke='%2381d4fa20' stroke-width='2'/%3E%3Cpath d='M30 20 L25 15 M30 20 L35 15 M30 40 L25 45 M30 40 L35 45' stroke='%2329b6f618' stroke-width='2'/%3E%3Cpolygon points='30,25 33,30 30,35 27,30' fill='%2381d4fa15' /%3E%3C/svg%3E")`, Neutral: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='30' cy='30' r='20' fill='none' stroke='%2390909010' stroke-width='1'/%3E%3Ccircle cx='30' cy='30' r='10' fill='none' stroke='%2390909008' stroke-width='1'/%3E%3C/svg%3E")`,
};

const CARD_TEXTURES = {
    none: '',
    grid: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='grid' width='20' height='20' patternUnits='userSpaceOnUse'%3E%3Cpath d='M20 0L0 0 0 20' fill='none' stroke='black' stroke-width='2'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23grid)'/%3E%3C/svg%3E")`,
    scales: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='scales' width='20' height='10' patternUnits='userSpaceOnUse'%3E%3Cpath d='M0 10 Q10 20 20 10 M10 0 Q20 10 30 0 M-10 0 Q0 10 10 0' fill='none' stroke='black' stroke-width='2'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23scales)'/%3E%3C/svg%3E")`,
    cross: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='cross' width='20' height='20' patternUnits='userSpaceOnUse'%3E%3Cpath d='M10 5v10M5 10h10' fill='none' stroke='black' stroke-width='3' stroke-linecap='round'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23cross)'/%3E%3C/svg%3E")`,
    stars: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='stars' width='30' height='30' patternUnits='userSpaceOnUse'%3E%3Cpath d='M15 5l3 7 7 3-7 3-3 7-3-7-7-3 7-3z' fill='black'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23stars)'/%3E%3C/svg%3E")`,
    hexagons: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='hex' width='28' height='49' patternUnits='userSpaceOnUse'%3E%3Cpath d='M14 0l14 8.1v16.2l-14 8.1L0 24.3V8.1z' fill='none' stroke='black' stroke-width='2'/%3E%3Cpath d='M14 49V32.4' stroke='black' stroke-width='2'/%3E%3Cpath d='M0 8.1L-14 0m28 0l14 8.1' stroke='black' stroke-width='2'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23hex)'/%3E%3C/svg%3E")`,
    lines: `url("data:image/svg+xml,%3Csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3E%3Cdefs%3E%3Cpattern id='lines' width='20' height='20' patternUnits='userSpaceOnUse' patternTransform='rotate(45)'%3E%3Cline x1='0' y1='0' x2='0' y2='20' stroke='black' stroke-width='3'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100%25' height='100%25' fill='url(%23lines)'/%3E%3C/svg%3E")`,
    dots: `url("data:image/svg+xml,%3Csvg width='20' height='20' viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='10' cy='10' r='2.5' fill='black'/%3E%3C/svg%3E")`,
    waves: `url("data:image/svg+xml,%3Csvg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M21.184 20c.357-.13.72-.264 1.088-.402l1.768-.661C33.64 15.347 39.647 14 50 14c10.271 0 15.362 1.222 24.629 4.928.955.383 1.869.74 2.75 1.072h6.225c-2.51-.73-5.139-1.691-8.233-2.928C65.888 13.278 60.562 12 50 12c-10.626 0-16.855 1.397-26.66 5.063l-1.767.662c-2.475.923-4.66 1.674-6.724 2.275h6.335zm0-20C13.258 2.892 8.077 4 0 4V2c5.744 0 9.951-.574 14.85-2h6.334zM77.38 0C85.239 2.966 90.502 4 100 4V2c-6.842 0-11.386-.542-16.326-2h-6.292zM0 14c8.44 0 13.718-1.21 22.272-4.402l1.768-.661C33.64 5.347 39.647 4 50 4c10.271 0 15.362 1.222 24.629 4.928C84.112 12.722 89.438 14 100 14v-2c-10.271 0-15.362-1.222-24.629-4.928C65.888 3.278 60.562 2 50 2 39.374 2 33.145 3.397 23.34 7.063l-1.767.662C13.223 10.84 8.163 12 0 12v2z' fill='black' fill-rule='evenodd'/%3E%3C/svg%3E")`,
    circuit: `url("data:image/svg+xml,%3Csvg width='100' height='100' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10 10 L20 10 L20 30 L50 30 L50 10 M80 10 L80 40 L60 40 M10 80 L30 80 L30 60 L60 60 L60 80 M90 90 L80 90 L80 70 L50 70' fill='none' stroke='black' stroke-width='2'/%3E%3Ccircle cx='20' cy='30' r='3' fill='black'/%3E%3Ccircle cx='60' cy='40' r='3' fill='black'/%3E%3Ccircle cx='30' cy='60' r='3' fill='black'/%3E%3Ccircle cx='80' cy='70' r='3' fill='black'/%3E%3C/svg%3E")`,
};

const ELEMENT_PARTICLES = {
    Fire: { emoji: '🔥', alt: ['🔥', '✨'], count: 12, speed: 'fast', direction: 'up' },
    Water: { emoji: '💧', alt: ['🫧', '💦'], count: 12, speed: 'slow', direction: 'up' },
    Nature: { emoji: '🍃', alt: ['🌿', '🌸'], count: 11, speed: 'medium', direction: 'float' },
    Electric: { emoji: '⚡', alt: ['⚡', '⭐'], count: 9, speed: 'fast', direction: 'random' },
    Mystic: { emoji: '🔮', alt: ['✨', '💫'], count: 10, speed: 'slow', direction: 'float' },
    Fighting: { emoji: '💥', alt: ['💢', '⚡'], count: 8, speed: 'fast', direction: 'random' },
    Shadow: { emoji: '🌑', alt: ['💀', '👻'], count: 7, speed: 'slow', direction: 'down' },
    Metal: { emoji: '⚙️', alt: ['⛓️', '🔩'], count: 6, speed: 'slow', direction: 'float' },
    Light: { emoji: '✨', alt: ['⭐', '🌟'], count: 12, speed: 'medium', direction: 'radial' },
    Dragon: { emoji: '🐉', alt: ['💎', '🔥'], count: 6, speed: 'medium', direction: 'float' },
    Ice: { emoji: '❄️', alt: ['❅', '💎'], count: 14, speed: 'slow', direction: 'down' },
    Neutral: { emoji: '✦', alt: ['⚪', '◆'], count: 5, speed: 'slow', direction: 'float' },
};

const FONTS = [
    { id: 'nunito', name: 'Nunito', family: "'Nunito', sans-serif" },
    { id: 'poppins', name: 'Poppins', family: "'Poppins', sans-serif" },
    { id: 'roboto', name: 'Roboto', family: "'Roboto', sans-serif" },
    { id: 'oswald', name: 'Oswald', family: "'Oswald', sans-serif" },
    { id: 'playfair', name: 'Playfair Display', family: "'Playfair Display', serif" },
    { id: 'bangers', name: 'Bangers', family: "'Bangers', cursive" },
    { id: 'cinzel', name: 'Cinzel', family: "'Cinzel', serif" },
    { id: 'dancing', name: 'Dancing Script', family: "'Dancing Script', cursive" },
    { id: 'orbitron', name: 'Orbitron', family: "'Orbitron', sans-serif" },
    { id: 'amatic', name: 'Amatic SC', family: "'Amatic SC', cursive" },
];

const PARTICLE_ANIMATIONS = [
    { key: 'fire', label: 'Rising (Fire)' },
    { key: 'water', label: 'Bubbles (Water)' },
    { key: 'nature', label: 'Floating (Nature)' },
    { key: 'electric', label: 'Sparks (Electric)' },
    { key: 'mystic', label: 'Magic (Mystic)' },
    { key: 'fighting', label: 'Impact (Fighting)' },
    { key: 'shadow', label: 'Fade (Shadow)' },
    { key: 'metal', label: 'Gears (Metal)' },
    { key: 'light', label: 'Radiate (Light)' },
    { key: 'dragon', label: 'Majestic (Dragon)' },
    { key: 'ice', label: 'Snow (Ice)' },
    { key: 'neutral', label: 'Subtle (Neutral)' }
];

const getInitialCardData = (t) => ({
    name: t.defaults.cardName, hp: 120, type: 'Fire', stage: 'Base', weakness: '💧', resistance: '🌿', retreatCost: 2, description: t.defaults.description, author: t.defaults.author, font: 'nunito', borderColor: '', backgroundColor: '', abilityBackground: 'rgba(255, 255, 255, 0.7)', textColor: '', nameColor: '', hpColor: '', typeColor: '', descColor: '', statsColor: '', authorColor: '', showHP: true, showWeakRes: true, showRetreat: true, showDescription: true, showParticles: true,
    colorMode: 'solid', primaryColor: '#ff6b35', secondaryColor: '#ff9e80', customIcon: '🔥', particleEmoji: '🔥', particleAnimation: 'fire',
    cardInnerBackground: 'rgba(255, 255, 255, 0.95)', cardInnerColorMode: 'solid', cardInnerSecondaryBackground: '#f5f5fa',
    texture: 'none', cardBack: null,
    /* Card Back Customization */
    cardBackPrimaryColor: '', cardBackSecondaryColor: '', cardBackGradientType: 'radial', cardBackGradientAngle: 135,
    cardBackShowCenterIcon: true, cardBackShowCornerIcons: true, cardBackShowFrame: true, cardBackShowBorder: true,
    cardBackTexture: 'none', cardBackTextureColor: '#000000',
    /* Typography Defaults */
    nameSize: 16, nameWeight: '700', hpSize: 18, hpWeight: '700', stageSize: 9, stageWeight: '700', descSize: 8, descWeight: '400', statsSize: 8, statsWeight: '400', authorSize: 6, authorWeight: '400', moveNameSize: 12, moveNameWeight: '700', moveDescSize: 8, moveDescWeight: '400',
});

const getInitialAttacks = (t) => ([
    { id: '1', name: t.defaults.attackName1, damage: 60, cost: 2, desc: t.defaults.attackDesc1, showDamage: true, background: 'rgba(255, 255, 255, 0.7)', colorMode: 'solid', secondaryBackground: '#ffffff' },
    { id: '2', name: t.defaults.attackName2, damage: 90, cost: 3, desc: t.defaults.attackDesc2, showDamage: true, background: 'rgba(255, 255, 255, 0.7)', colorMode: 'solid', secondaryBackground: '#ffffff' },
]);

const INITIAL_IMAGE_SETTINGS = {
    zoom: 1, offsetX: 0, offsetY: 0,
};
